In [1]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.io as pio


file_path = '/home/student/Documents/VKV/AWG/VKV/preProccessed_data/ESA_31_Aug_25/IQTool_LFM_fc_2ghz_bw_2ghz_pw_2mus_ri_2mus_amp_550mV - IQTool_LFM_fc_2ghz_bw_2ghz_pw_2mus_ri_2mus_amp_550mV.csv'
df = pd.read_csv(file_path)
df['Frequency (Hz)'] = df['Frequency (Hz)']/1e9
df.head(5)

   Frequency (Hz)  Power (dBm)
0        0.010000   -77.023071
1        0.010312  -139.562873
2        0.010624   -77.329521
3        0.010937  -135.964606
4        0.011249   -76.667336

In [2]:
fig = go.Figure()

fig.add_trace(go.Scatter(x = df['Frequency (Hz)'], y = df['Power (dBm)'], mode= 'lines'))
fig.update_layout(
                  title = 'LFM generated using IQ tools with center frequency 2 GHz BW 2 GHz, PW 2 us, and RI 2 us',
                  xaxis_title = 'Frequency (GHz)',
                  yaxis_title = 'Power (dBm)'
)
fig.show()

In [3]:
file_path = '/home/student/Documents/VKV/AWG/VKV/preProccessed_data/ESA_31_Aug_25/GUI_LFM_fc_2ghz_bw_2ghz_pw_2mus_ri_2mus_amp_550mV - GUI_LFM_fc_2ghz_bw_2ghz_pw_2mus_ri_2mus_amp_550mV.csv'
df = pd.read_csv(file_path)
df['Frequency (Hz)'] = df['Frequency (Hz)']/1e9
df.head(5)

   Frequency (Hz)  Power (dBm)
0        0.010000   -76.545685
1        0.010312  -131.145240
2        0.010624   -76.983688
3        0.010937  -129.151343
4        0.011249   -77.256340

In [4]:
fig = go.Figure()

fig.add_trace(go.Scatter(x = df['Frequency (Hz)'], y = df['Power (dBm)'], mode= 'lines'))
fig.update_layout(
                  title = 'LFM Generated using GUI with center frequency 2 GHz BW 2 GHz, PW 2 us, and RI 2 us',
                  xaxis_title = 'Frequency (GHz)',
                  yaxis_title = 'Power (dBm)'
)
fig.show()

In [5]:
file_path = '/home/student/Documents/VKV/AWG/VKV/preProccessed_data/ESA_31_Aug_25/GUI_LFM_fc_2ghz_bw_2ghz_pw_2mus_ri_2mus_amp_250mV - GUI_LFM_fc_2ghz_bw_2ghz_pw_2mus_ri_2mus_amp_250mV.csv'
daf = pd.read_csv(file_path)
daf['Frequency (Hz)'] = df['Frequency (Hz)']
daf.head(5)

   Frequency (Hz)  Power (dBm)
0        0.010000   -75.283798
1        0.010312  -136.541144
2        0.010624   -76.546402
3        0.010937  -145.037726
4        0.011249   -76.467018

In [6]:
fig = go.Figure()

fig.add_trace(go.Scatter(x = daf['Frequency (Hz)'], y = daf['Power (dBm)'], mode= 'lines'))
fig.update_layout(
                  title = 'LFM Generated using GUI with center frequency 2 GHz BW 2 GHz, PW 2 us, RI 2 us, and amplitude 250 mV',
                  xaxis_title = 'Frequency (GHz)',
                  yaxis_title = 'Power (dBm)'
)
fig.show()

In [7]:
file_path = '/home/student/Documents/VKV/AWG/VKV/preProccessed_data/ESA_31_Aug_25/awg_sine_2ghz - awg_sine_2ghz.csv'
df = pd.read_csv(file_path)
df['Frequency (Hz)'] = df['Frequency (Hz)']/1e9
df.head(5)

   Frequency (Hz)  Power (dBm)
0          0.5000   -71.468621
1          0.5095   -95.261712
2          0.5190   -71.206757
3          0.5285  -101.290978
4          0.5380   -70.861268

In [8]:
fig = go.Figure()

fig.add_trace(go.Scatter(x = df['Frequency (Hz)'], y = df['Power (dBm)'], mode= 'lines'))
fig.update_layout(
                  title = 'Sine Generated using AWG Soft Panel with frequency 2 GHz and amplitude 300 mV',
                  xaxis_title = 'Frequency (GHz)',
                  yaxis_title = 'Power (dBm)'
)
fig.show()

In [9]:
file_path = '/home/student/Documents/VKV/AWG/VKV/preProccessed_data/ESA_31_Aug_25/sine_2ghz - sine_2ghz.csv'
df = pd.read_csv(file_path)
df['Frequency (Hz)'] = df['Frequency (Hz)']/1e9
df.head(5)

   Frequency (Hz)  Power (dBm)
0           1.000   -71.259751
1           1.009   -96.459092
2           1.018   -71.753297
3           1.027   -95.843926
4           1.036   -71.691941

In [10]:
fig = go.Figure()

fig.add_trace(go.Scatter(x = df['Frequency (Hz)'], y = df['Power (dBm)'], mode= 'lines'))
fig.update_layout(
                  title = 'Sine Generated using GUI with frequency 2 GHz and amplitude 300 mV',
                  xaxis_title = 'Frequency (GHz)',
                  yaxis_title = 'Power (dBm)'
)
fig.show()

In [11]:
file_path = '/home/student/Documents/VKV/AWG/VKV/preProccessed_data/ESA_31_Aug_25/AWG_without_signal_8ghz - AWG_without_signal_8ghz.csv'
df = pd.read_csv(file_path)
df['Frequency (Hz)'] = df['Frequency (Hz)']/1e9
df.head(5)

   Frequency (Hz)  Power (dBm)
0        0.010000  -106.865188
1        0.010312  -141.082725
2        0.010624  -106.679969
3        0.010937  -137.325721
4        0.011249  -105.353393

In [12]:
fig = go.Figure()

fig.add_trace(go.Scatter(x = df['Frequency (Hz)'], y = df['Power (dBm)'], mode= 'lines'))
fig.update_layout(
                  title = 'signals from AWG without any waveform generation',
                  xaxis_title = 'Frequency (GHz)',
                  yaxis_title = 'Power (dBm)'
)
fig.show()